server:
  port: 8080

spring:
  profiles:
    active: prod  # 或 local，视你实际环境而定

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=gateway-env, springcloud-gateway
      routes:
        - id: user_route
          uri: http://user-center:8087
          predicates:
            - Path=/user/**
          filters:
            - PreserveHostHeader
        - id: game_route
          uri: http://game-center:8089
          predicates:
            - Path=/game/**
          filters:
            - PreserveHostHeader
        - id: lobby_route
          uri: http://lobby-center:8088
          predicates:
            - Path=/api/**
          filters:
            - PreserveHostHeader

  codec:
    max-in-memory-size: 5MB